import {
  Boxes,
  Droplets,
  Flame,
  Heart,
  House,
  KeyRound,
  LayoutDashboard,
  LifeBuoy,
  Lock,
  LogOut,
  Package,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Store,
  User,
  Video,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@workspace/types";

export const iconRegistry: Record<IconName, LucideIcon> = {
  house: House,
  store: Store,
  droplets: Droplets,
  flame: Flame,
  video: Video,
  "shield-check": ShieldCheck,
  search: Search,
  sliders: SlidersHorizontal,
  "layout-dashboard": LayoutDashboard,
  package: Package,
  boxes: Boxes,
  heart: Heart,
  "life-buoy": LifeBuoy,
  user: User,
  settings: Settings,
  lock: Lock,
  "log-out": LogOut,
  "key-round": KeyRound,
};